# Generated by Django 5.1.1 on 2024-09-04 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'jogo',
            },
        ),
        migrations.CreateModel(
            name='JogoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.jogo')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.plataforma')),
            ],
            options={
                'db_table': 'jogo_jogoplataforma',
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataformas',
            field=models.ManyToManyField(through='jogo.JogoPlataforma', to='plataforma.plataforma'),
        ),
    ]
