# Generated by Django 5.1.1 on 2024-09-04 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('jogo_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.jogoplataforma')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacao.locacao')),
            ],
        ),
    ]
